# Default Settings for MushkilViz

# Analysis settings
analysis:
  outlier_detection:
    method: zscore
    threshold: 3.0
  correlation:
    method: pearson
  dimensionality_reduction:
    method: pca
    n_components: 2

# Visualization settings
visualization:
  color_scheme:
    primary: "#3498db"    # Blue
    secondary: "#2ecc71"  # Green
    accent: "#e74c3c"     # Red
    neutral: "#95a5a6"    # Gray
  plot_style:
    template: "plotly_white"
    font_family: "Arial"
    title_font_size: 24
    axis_font_size: 12
    show_grid: true

# Report generation
report:
  format: html
  include_table_of_contents: true
  sections:
    - title: "Overview"
      plots:
        - dataset_info
        - correlation_matrix
    - title: "Distribution Analysis"
      plots:
        - numeric_distributions
        - categorical_distributions
    - title: "Advanced Analysis"
      plots:
        - dimension_reduction
        - outlier_detection 