name: mushkil-viz
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.18.0
  - altair>=5.1.0
  - umap-learn>=0.5.0
  - xgboost>=2.0.0
  - pycaret>=3.1.0
  - statsmodels>=0.14.0
  - scipy>=1.11.0
  - spacy>=3.7.0
  - rapidfuzz>=3.4.0
  - jinja2>=3.1.0
  - weasyprint>=60.1
  - typer>=0.9.0
  - pyyaml>=6.0.0
  - dask>=2023.12.0
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - pip
  - pip:
      - openai==1.63.2
      - faker>=20.0.0
      - -e .
  - openai
  - python-dotenv
