# Financial Domain Configuration

# Column pattern matching rules
column_patterns:
  transaction_amount:
    - amount
    - transaction
    - payment
    - price
    - debit
    - credit
  merchant:
    - merchant
    - vendor
    - payee
    - recipient
    - store
  category:
    - category
    - type
    - description
    - classification
  date:
    - date
    - time
    - timestamp
    - posted
    - processed

# Analysis settings
analysis:
  outlier_detection:
    method: zscore
    threshold: 3.0
  recurring_transactions:
    amount_threshold: 0.1
    frequency_threshold: 2
  spending_patterns:
    top_merchants_limit: 10
    min_category_frequency: 5
  cash_flow:
    inflow_threshold: 0.0
    include_pending: false

# Visualization settings
visualization:
  color_scheme:
    positive: "#2ecc71"  # Green
    negative: "#e74c3c"  # Red
    neutral: "#3498db"   # Blue
  spending_trends:
    chart_type: line
    show_moving_average: true
    moving_average_window: 7
  category_breakdown:
    chart_type: sunburst
    max_categories: 15
    other_category_threshold: 0.02
  merchant_analysis:
    chart_type: bar
    orientation: horizontal
    top_n: 10
  cash_flow:
    chart_type: waterfall
    show_percentages: true
  recurring_transactions:
    chart_type: scatter
    min_frequency: 2
    marker_size_factor: 2

# Report generation
report:
  sections:
    - title: "Overview"
      plots:
        - spending_trends
        - cash_flow
    - title: "Spending Analysis"
      plots:
        - category_breakdown
        - merchant_analysis
    - title: "Patterns & Insights"
      plots:
        - recurring_transactions
        - correlation_matrix
  format:
    page_size: A4
    orientation: portrait
    include_table_of_contents: true 