# LLM Domain Configuration

# Visualization settings
visualization:
  color_scheme:
    primary: "#3498db" # Blue
    secondary: "#2ecc71" # Green
    accent: "#e74c3c" # Red
    neutral: "#95a5a6" # Gray

  chart_defaults:
    bar:
      opacity: 0.8
      orientation: "v"
      text_auto: true

    line:
      mode: "lines+markers"
      marker_size: 6

    scatter:
      mode: "markers"
      marker_size: 8

    histogram:
      nbins: 30
      opacity: 0.7

    heatmap:
      colorscale: "Viridis"

  layout:
    font_family: "Arial, sans-serif"
    title_font_size: 16
    axis_font_size: 12
    margin:
      t: 50
      r: 50
      b: 50
      l: 50
    showlegend: true
    paper_bgcolor: "white"
    plot_bgcolor: "white"
    grid:
      show: true
      color: "#ecf0f1"
      width: 1

report:
  sections:
    - title: "Dataset Overview"
      description: "Basic information about the dataset including size, structure, and key distributions."
      visualizations:
        - categorical_distributions
        - numeric_distributions
        - temporal_patterns

    - title: "Feature Analysis"
      description: "Analysis of key features and their relationships."
      visualizations:
        - feature_correlations
        - feature_distributions
        - outlier_analysis

    - title: "Relationships & Patterns"
      description: "Key relationships and patterns discovered in the data."
      visualizations:
        - key_relationships
        - trend_analysis
        - group_comparisons

    - title: "Additional Insights"
      description: "Other relevant visualizations and insights discovered in the data."
      visualizations:
        - custom_insights
