# Analysis settings
analysis:
  outlier_detection:
    method: zscore
    threshold: 3.0
  correlation:
    method: pearson
    threshold: 0.7
  dimensionality_reduction:
    method: pca
    n_components: 2

# Visualization settings
visualization:
  color_scheme:
    primary: "#2C3E50"
    secondary: "#E74C3C"
    accent: "#3498DB"
    background: "#ECF0F1"
  plot_style:
    font_family: "Arial"
    title_size: 16
    label_size: 12
    tick_size: 10
    legend_size: 10
    figure_size: [10, 6]

# Report generation settings
report:
  format: html
  include_toc: true
  sections:
    - title: "Dataset Overview"
      plots:
        - distribution
        - correlation_matrix
    - title: "Feature Analysis"
      plots:
        - box_plots
        - scatter_matrix
    - title: "Dimensionality Reduction"
      plots:
        - pca_plot
        - tsne_plot 